"""empty message

Revision ID: 5929dc9c624a
Revises: 653d68312991
Create Date: 2021-08-20 12:26:57.567531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5929dc9c624a'
down_revision = '653d68312991'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'department')
    # ### end Alembic commands ###


def upgrade_second():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__second', sa.Column('department', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade_second():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__second', 'department')
    # ### end Alembic commands ###
