"""empty message

Revision ID: 5a77262c502b
Revises: dd7c69423ad9
Create Date: 2021-08-20 11:57:30.389344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a77262c502b'
down_revision = 'dd7c69423ad9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date')
    # ### end Alembic commands ###


def upgrade_second():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__second', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_second():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__second', 'date')
    # ### end Alembic commands ###
